### ISSUE TITLE
Can this project be more general?

### ISSUE THREAD

**Issue by yanxiang-wang** [pnkraemer/tueplots#108]
For instance, there can be default settings for single/double-column scenarios instead of for one specific conference.

**Comment by pnkraemer** [comment]
Thanks for reaching out. Do you have something specific in mind? 

I am not against a change like this, but I am asking because it is not obvious to me at the moment what this default setting would be doing, i.e., which figure sizes, font sizes, etc., it would create. 

But nothing stops us from using, e.g., `bundles.icml2022()`  configs for unrelated scenarios. I do this myself all the time :) Maybe there is a way of improving the documentation to make reusing existing styles a little bit easier. What do you think?

**Comment by yanxiang-wang** [comment]
I agree with you. Well, I just want to find optimal settings for other publication targets. For instance, there are two templates that most CS researchers use: one is IEEE, and another one is ACM. If we can also define some styles for these two templates, I think more people will like to use this project.

**Comment by pnkraemer** [comment]
Thanks for clarifying. This sounds reasonable. 

I think the best way forward here would be to implement a specific `ieee` format, and/or a specific `acm` format.  
Do you have a specific template in mind? If so, I would gladly review a pull request on this..
